url: https://aleatory.science
baseurl:

# Site settings
title: Aleatory Science
logo: aleatory_science_logo.svg
# email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Thomas Wim Hamelryck
  # pic: 1
  modal-id: 1
  position: Associate Professor (PI)
  social:
    - title: github
      url: https://github.com/thamelry #

- name: Fritz Henglein
  # pic: 2
  modal-id: 2
  position: Professor
  social:
    - title: github
      url: https://github.com/henglein #

- name: Ahmad Salim Al-Sibahi
  pic: ahmadsalim
  modal-id: 3
  position: Assistant Professor
  description: |
    Ahmad Salim Al-Sibahi is an Assistant Professor at Department of Computer Science, University of Copenhagen. He works on inference algorithms for powering protein folding.

    He previously was at Skanned and Department of Computer Science, University of Copenhagen, working with Thomas Hamelryck and Fritz Henglein. There, he working on how to use probabilistic programming to improve the scanning component of Skanned’s API.

    He was previously a PhD Fellow and Postdoc at the IT University of Copenhagen as a part of the Software Quality Research group, under the supervision of Andrzej Wąsowski and Aleksandar Dimovski. His PhD project was about how to practically use programming language techniques to analyze high-level transformation programs. During his PhD, he had a research visit to the Celtique group at INRIA Rennes, working with Thomas Jensen.

    He was also recently a contributor to the dependently-typed programming language Idris.
  social:
    - title: github
      url: https://github.com/ahmadsalim

- name: Ola Rønning
  pic: ola
  modal-id: 4
  position: PhD Fellow
  social:
    - title: github
      url: https://github.com/OlaRonning
    - title: linkedin
      url: https://www.linkedin.com/in/ola-rønning-bb323082/

- name: Lys Sanz Moreta
  modal-id: 5
  position: PhD Fellow

- name: Robert Schenck
  modal-id: 6
  position: PhD Fellow
  social:
    - title: github
      url: https://github.com/zfnmxt

- name: Christian Thygesen
  modal-id: 7
  pic: christian
  position: Industrial PhD Fellow (Evaxion)
  social:
    - title: github
      url: https://github.com/cthyge
    - title: linkedin
      url: https://linkedin.com/in/cthyge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/aleatory-science

# Postal address (add as many lines as necessary)
address:
  - line: Probabilistic Programming Group
  - line: Programming Language and Theory of Computation Section
  - line: Department of Computer Science, University of Copenhagen

# Build settings
markdown: kramdown
permalink: pretty
