url: https://aleatory.science
baseurl:

# Site settings
title: Aleatory Science
logo: aleatory_science_logo.svg
# email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Thomas Wim Hamelryck
  # pic: 1
  position: Associate Professor (PI)
  social:
    - title: github
      url: https://github.com/thamelry #

- name: Fritz Henglein
  # pic: 2
  position: Professor
  social:
    - title: github
      url: https://github.com/henglein #

- name: Ahmad Salim Al-Sibahi
  pic: ahmadsalim
  position: Assistant Professor
  social:
    - title: github
      url: https://github.com/ahmadsalim

- name: Ola Rønning
  position: PhD Fellow

- name: Lys Sanz Moreta
  position: PhD Fellow

- name: Robert Schenck
  position: PhD Fellow
  social:
    - title: github
      url: https://github.com/zfnmxt

- name: Christian Thygesen
  pic: christian
  position: Industrial PhD Fellow (Evaxion)
  social:
    - title: github
      url: https://github.com/cthyge
    - title: linkedin
      url: https://linkedin.com/in/cthyge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/aleatory-science

# Postal address (add as many lines as necessary)
address:
  - line: Probabilistic Programming Group
  - line: Programming Language and Theory of Computation Section
  - line: Department of Computer Science, University of Copenhagen

# Build settings
markdown: kramdown
permalink: pretty
